### ISSUE TITLE
EU flag not accessible

### ISSUE THREAD

**Issue by dhoehl** [blongho/worldCountryData#11]
The newly added eu flag is not accessible via World.getFlagOf("EU"). Only the globe is retrieved.

**Comment by blongho** [comment]
Hello @dhoehl ,
Try this `implementation 'com.github.blongho:worldCountryData:11e095b585'`and let us know if it solves your problem.

Bernard

**Comment by dhoehl** [comment]
> 
> 
> Hello @dhoehl ,
> Try this `implementation 'com.github.blongho:worldCountryData:11e095b585'`and let us know if it solves your problem.
> 
> Bernard

Yes it does.
