### ISSUE TITLE
Fallback drawable

### ISSUE THREAD

**Issue by chitgoks** [blongho/worldCountryData#13]
Hi, would be to nice to have an option to have a custom fallback drawable or we can set a default flag as fallback

**Comment by funyin** [comment]
I was just thinking of the same thing a while back. Although blongho did a great job with the globe drawable as a fallback

**Comment by blongho** [comment]
As noticed by @funyin , there is the `globe` drawable as fall-back. If nothing is found, the globe(World.globe()) is returned

**Comment by chitgoks** [comment]
yes. i saw that. its ok. it was a suggestion if we can have our own custom fallback drawable right away

instead of doing manual if else
