### ISSUE TITLE
Taiwan and USA flag are small

### ISSUE THREAD

**Issue by chitgoks** [blongho/worldCountryData#14]
Use 
@drawable/tw 
@drawable/usa
to replicate

**Comment by chitgoks** [comment]
us flag is also incorrect. the top line is white, it should be red right?

**Comment by blongho** [comment]
What is the size of the ImageView. I do not experience this in this project 
[https://github.com/blongho/world-country-data-demo ](https://github.com/blongho/world-country-data-demo )

You can download the apk from Google play and try it [https://play.google.com/store/apps/details?id=com.blongho.countrydata](https://play.google.com/store/apps/details?id=com.blongho.countrydata)

**Comment by chitgoks** [comment]
closing this. i decided to use remote images instead
