### ISSUE TITLE
minsdk should be 21

### ISSUE THREAD

**Issue by chitgoks** [blongho/worldCountryData#16]
hi correct me if im wrong

shouldn't min sdk be 21 instead of the current 15? there would be no point to have those vector images since it will still generate pngs.

**Comment by blongho** [comment]
I will make a patch with the minsdk 21. I think you are correct about the vector images.

**Comment by chitgoks** [comment]
thanks blongho!

**Comment by blongho** [comment]
Hi @chitgoks 
What is your experience with this
```
    implementation 'com.github.blongho:worldCountryData:ffa9b81b7c'
```

**The only change there is upgrading the min-sdk to 21.**

**Comment by chitgoks** [comment]
Hmm same result. weird. i have no idea why. i already set min sdk to 21 in my project and explicitly set vectorDrawables.useSupportLibrary to false

**Comment by blongho** [comment]
Evidently, changing the minSdk to 21 does not resolve your problem. I will close this issue

**Comment by chitgoks** [comment]
agreed
