### ISSUE TITLE
Problem with implementation

### ISSUE THREAD

**Issue by ghost** [blongho/worldCountryData#17]
**Describe the bug**
Cannot implement the library.
` implementation 'com.github.blongho:worldCountryData:v1.5'`
`implementation 'com.github.blongho:worldCountryData:1.5'`

**Error**
```
Failed to resolve: com.github.blongho:worldCountryData:1.5
Show in Project Structure dialog
Affected Modules: app
```

Android Studio 4.0

**Comment by blongho** [comment]
I am curious how you solved that

**Comment by ghost** [comment]
Sorry for this issue, I don't know how to delete it (is it possible?)I just forget to add JitPack.

**Comment by blongho** [comment]
It is ok. Any one can make that error. Glad you figured it.
