### ISSUE TITLE
Invalid data

### ISSUE THREAD

**Issue by TadesseAngaw** [blongho/worldCountryData#2]
The JSON data for some countries invalid 

for example, the country code of Ethiopia is 251 but in the data, it is 231

**Comment by blongho** [comment]
Hi, @TadesseAngaw  thanks for pointing that out. 
 
I think you are mixing the country calling code (251) and the country iso 3166 numeric code (231). In this library, country code refers to the iso 3166 numeric code for country.

**Refer to** [iso 3166 code for Ethiopia](https://www.iso.org/obp/ui/#iso:code:3166:ET), **[List of all iso 3166 codes](https://www.iso.org/obp/ui/#search)** and **[Definitions](https://www.iso.org/glossary-for-iso-3166.html)**

Hope this clarifies any doubts. I will update the documentation to make this clearer. 

By the way, are you interested in getting the calling codes? This is envisaged in future releases see [features list](https://github.com/blongho/world-country-data/wiki/Features-list)

**Comment by TadesseAngaw** [comment]
Thank you. Closing the issue now.
