### ISSUE TITLE
test

### ISSUE THREAD

**Issue by anilthummar** [blongho/worldCountryData#20]
still getting issues in signup apk file

**Comment by MuzaffarAbduboqiyev** [comment]
I got like that issue. If you find solution, share it pls

**Comment by anilthummar** [comment]
> I got like that issue. If you find solution, share it pls

Yes 

set this

minifyEnabled false

in your app build.gradle

**Comment by blongho** [comment]
@anilthummar  thanks. 
@MuzaffarAbduboqiyev  if this does not help, then see #18
