### ISSUE TITLE
String.toLowerCase()' on a null object reference com.blongho.country_data.WorldData.getCurrencies

### ISSUE THREAD

**Issue by chitgoks** [blongho/worldCountryData#21]
Caused by java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
com.blongho.country_data.WorldData.getCurrencies (WorldData.java:31)

I reported this based on getCurrencies() i didnt use this method so problem could be inside. perhaps a check if string is null?

**Comment by blongho** [comment]
I have checked and it seems some countries lack currency and some lack currency symbol. Controll for non-null on these before working on them.

This issue is addressed in the soon to be released version.

**Comment by blongho** [comment]
You can check my implementation here  and see how i checked for null 
[https://github.com/blongho/world-country-data-demo/blob/master/app/src/main/java/com/blongho/countrydata/viewmodel/CountryRepository.java#L67](https://github.com/blongho/world-country-data-demo/blob/master/app/src/main/java/com/blongho/countrydata/viewmodel/CountryRepository.java#L67)
