### ISSUE TITLE
Flag cut off in ImageView.

### ISSUE THREAD

**Issue by chitgoks** [blongho/worldCountryData#22]
Hi. I use the svg to this ImageView tag.

```
<ImageView
			android:id="@+id/flag"
			android:layout_width="30dp"
			android:layout_height="20dp"
			android:layout_marginEnd="5dp"
			android:contentDescription="@string/empty"
			android:layout_gravity="center_vertical"
			android:scaleType="centerCrop"/>

```
For example, use american flag. The result is not all the flag is fit inside the ImageView.

tried to use adjustViewBounds, still no. tried all scale types, nothing worked such that the flag did not fit in the image view.

please seee result.
![flag](https://user-images.githubusercontent.com/3955470/96356842-9d466d80-1126-11eb-9add-2259338c29be.png)

e.g. US and PH flag are cut off.

thoughts?

**Comment by blongho** [comment]
I do not notice that kind of behaviour. Check this application
https://github.com/blongho/world-country-data-demo

It has an apk that you can download from Google play

**Comment by chitgoks** [comment]
ok anyway. they are 72dp both in width and height in the sample which is not what i want.

it's ok. not a bottleneck.
