### ISSUE TITLE
cant use World.init(getApplication());

### ISSUE THREAD

**Issue by jomarierafa** [blongho/worldCountryData#3]
im using androidx and kotlin
i can't use World

the build is successful
implementation 'com.github.blongho:world-country-data:1.3-alpha'

**Comment by olehka** [comment]
I have the same problem :(

**Comment by blongho** [comment]
Will try to **fix**  in the days ahead...

**Comment by blongho** [comment]
Hi, @jomarierafa The issue is now fixed with v1.4-beta
