### ISSUE TITLE
Build fails on pipeline

### ISSUE THREAD

**Issue by phomotech** [blongho/worldCountryData#38]
The build on pipeline fails because of the below reason 

Failed to transform worldCountryData-1.5.2.jar (com.github.blongho:worldCountryData:1.5.2) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Could not find worldCountryData-1.5.2.jar (com.github.blongho:worldCountryData:1.5.2).
        Searched in the following locations:
            https://jitpack.io/com/github/blongho/worldCountryData/1.5.2/worldCountryData-1.5.2.jar

**Comment by EmiliaPoruszek** [comment]
I have same issue with 1.5.1

**Comment by EmiliaPoruszek** [comment]
It mind be related to the fact that such link doesn't exist.
https://jitpack.io/com/github/blongho/worldCountryData/1.5.2/ shows that the proper place is https://jitpack.io/com/github/blongho/worldCountryData/1.5.2/worldCountryData-1.5.2-sources.jar
But from some reason Gradle search for different place.

**Comment by fatonhoti** [comment]
@EmiliaPoruszek @phomotech Have you tried using the latest version `v1.5.3` in your module specific `build.gradle` file? `implementation 'com.github.blongho:worldCountryData:1.5.3'` Version `v1.5.2` was never a full release. Also check that you're targeting the correct SDK versions (`targetSdkVersion 31`) for the application.

**Comment by phomotech** [comment]
Yes I was on latest version ...

Adding the below code to the setting grade and build Gradle solved my issue on the pipeline 
//App Level build.gradle

allprojects {
    repositories {
        //...
      maven { url 'https://www.jitpack.io' }  // maven { url 'https://jitpack.io' }
    }
}

//Setting,gradle
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        jcenter() // Warning: this repository is going to shut down soon
        maven { url 'https://jitpack.io' }
    }
}

**Comment by fatonhoti** [comment]
@phomotech Feel free to close/delete the issue if your problem has been resolved.
