### ISSUE TITLE
Problem with implementation

### ISSUE THREAD

**Issue by Sokamn** [blongho/worldCountryData#41]
Hello, I wanted to know if anyone has ever had this problem.

Could not find com.github.blongho:worldCountryData:v1.5.3.
Required by:
    project :app
Search in build.gradle files

I saw someone with this problem, and it was because he didn't write JitPack in repositories. (Problem with implementation)

So, I think I have the same problem, since other libraries don't work for me either, do you know any solution?

Thanks and regards.

**Comment by blongho** [comment]
Hej @Sokamn , 
Please check this demo project [world country data demo](https://github.com/blongho/world-country-data-demo) if to see if it helps.
