### ISSUE TITLE
Some countries doesn`t have flags

### ISSUE THREAD

**Issue by Radcat501** [blongho/worldCountryData#42]
Hello! 

I am using function:
`World.getFlagOf(item.CodeAlpha2)`

Works fine, but some countries and regions does not have flags:

- Saint Maarten
- Turkmenistan
- Gibraltar
- French Polynesia
- New Caledonia
- Wallis and Futuna
- Indonesia
- Guernsey
- Ghana
- Hong Kong
- Macao

Thank you.

**Comment by blongho** [comment]
@Radcat501 Thanks for this. I am currently looking at the issue. Will be fixed in the days ahead

**Comment by blongho** [comment]
@Radcat501 Thanks for this feedback. There was an implementation issue that excluded countries without currencies or whose currencies lacked symbol and/or name. 

It is now left to the developer to make the check!

**Comment by NMSTEAM** [comment]
Thank you for fixes.

**Comment by Radcat501** [comment]
Thank you for fixes.
