### ISSUE TITLE
worldCountryData-1.4.aar is missing from the Jitpack repository

### ISSUE THREAD

**Issue by lclutz** [blongho/worldCountryData#43]
**Describe the bug**
The file `worldCountryData-1.4.aar` is missing from Jitpack.

**To Reproduce**
Try to build a project with a dependency on version 1.4

```
implementation 'com.github.blongho:worldCountryData:1.4'
```

It will result in the error message `Failed to resolve: worldCountryData-1.4`.

**Expected behavior**
Sucessful resolution of dependencies when using version 1.4.

**Additional context**
```
$ curl https://jitpack.io/com/github/blongho/worldCountryData/1.4/
build.log
worldCountryData-1.4-sources.jar
worldCountryData-1.4-sources.jar.md5
worldCountryData-1.4-sources.jar.sha1
worldCountryData-1.4.pom
worldCountryData-1.4.pom.md5
worldCountryData-1.4.pom.sha1
```

As you can see in the file listing above `worldCountryData-1.4.aar` is missing from the repository despite being mentioned in the `build.log`.

**Comment by blongho** [comment]
Hi @lclutz can you try a different version of the library.

**Comment by lclutz** [comment]
Hey @blongho,

I'm just bringing this up because I was trying to build an older code base that was relying on `1.4`.
You are correct, changing to version `1.5` for example works, but so would `1.4` if it wasn't for this issue in the Jitpack repository.
That's why I thought it's a problem worth mentioning. If you don't consider that a bug feel free to close this issue.
