### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference

### ISSUE THREAD

**Issue by mustafaberk1996** [blongho/worldCountryData#44]
**Describe the bug**
I am getting an error that is NullPointerException. It is in WorldData.java file where in this library.

**To Reproduce**

1. just write World.init(applicationContext) in App file or an Activity file.

**Expected behavior**

**Screenshots**
<img width="998" alt="Screen Shot 2022-11-30 at 12 24 49" src="https://user-images.githubusercontent.com/57665619/204758251-1d795628-0cd3-49f6-9076-756e4ed1cd22.png">

<img width="870" alt="Screen Shot 2022-11-30 at 12 24 59" src="https://user-images.githubusercontent.com/57665619/204758576-2734d38b-7448-46ca-a252-de726e71b746.png">

**Additional context**
I hadn't been getting this error before but now I am getting. It is weird I also use this library in my another app and this library is working as well there.

**Comment by blongho** [comment]
Hi @mustafaberk1996 ,

Which version of the library are you using?

**Comment by mustafaberk1996** [comment]
I was using the latest version but I removed the library. Now I am using [FlagKit](https://github.com/murgupluoglu/flagkit-android) library and there is no issue until now.

**Comment by IvLink-dev** [comment]
Hi @mustafaberk1996, I think you use proguard and forgot to add proguard rules
-keep class com.blongho.** {
    *;
}
-keep interface com.blongho.**
-keeppackagenames com.blongho.country_data
-keepclassmembers class com.blongho.country_data.* {
    public *;
}
-keep class com.blongho.country_data.R {
    *;
}

**Comment by waheedkhan-dev** [comment]
Facing same issue on a release build with isMinifyEnabled = true and  isShrinkResources = false 
Also add the proguard rules mention above
