### ISSUE TITLE
Amazing work!!! Could you give some tips to create flag xml?

### ISSUE THREAD

**Issue by Juderer** [blongho/worldCountryData#46]
Amazing work! I really appreciate it!

I used **Vector Asset** in Android Studio to generate xml files showing different countries' flags via [SVGs](https://github.com/hampusborgos/country-flags/tree/main/svg). 

But there is a problem. I try to use [EU FLAG SVG](https://github.com/hampusborgos/country-flags/blob/main/svg/eu.svg) to obtain [EU FLAG XML](https://github.com/blongho/worldCountryData/blob/master/country_data/src/main/res/drawable/eu.xml) and I will lost some five-pointed stars in vector drawable preview. The same goes for the [US FLAG SVG](https://github.com/hampusborgos/country-flags/blob/main/svg/us.svg). What they have in common is that they have lots of five-pointed stars.

So, could you share some tips about creating XML files via SVG files applying to Android applications?
THANKS A LOT!!!

**Comment by blongho** [comment]
@Juderer, @eagskunst did those changes. I think he can give you a better directive. He did change the images to .xml in the [pull request 8](https://github.com/blongho/worldCountryData/pull/8)

**Comment by eagskunst** [comment]
Hey @Juderer , it may be a problem with the svg resources I used.
You can add SVG as XML files with the Android asset tool:
1. Right click on the `res` folder of your module
2. New -> Vector Asset
<img width="573" alt="image" src="https://github.com/blongho/worldCountryData/assets/23042932/668d5a41-b1da-4e88-85b9-f622c262e7b5">


3. Local file, select the file path and press finish
<img width="708" alt="image" src="https://github.com/blongho/worldCountryData/assets/23042932/4b23154e-953c-456d-a3a9-216d3f63bc16">

**Comment by Juderer** [comment]
@blongho @eagskunst Thank you guys so much for the helpful responses!
