### ISSUE TITLE
Failed to resolve issue

### ISSUE THREAD

**Issue by RikNorakomi** [blongho/worldCountryData#6]
I am getting the ERROR: Failed to resolve

Whether I am using  _io.github.blongho:worldCountryData:1.3_ or

implementation '_com.github.blongho:worldCountryData:1.2.0_'

Added the maven repo to the gradle dependency, cleaned, rebuild project, invalidate cache & restart, but just cant seem to get this working?!
Can't seem to figure out how to solve this. Any help?

**Comment by blongho** [comment]
Dear RikNorakomi,
I am glad you find the library useful.

Please, upgrade to the latest version (v1.4-beta01). version v1.3 had a build issue that was fixed in v1.4-beta01.

Let me know if the upgrade solves your problem.

Give the project a star in order to be notified of the latest updates.

Kind regards
Bernard

**Comment by IkramulMurad** [comment]
I get below errors:
Failed to resolve: com.github.blongho:worldCountryData:v1.5.0
Failed to resolve: com.github.blongho:worldCountryData:1.5.0

for respective statements:
implementation 'com.github.blongho:worldCountryData:v1.5.0'
implementation 'com.github.blongho:worldCountryData:1.5.0'


I tried with v1.4-beta01, it also gets the error.

**Comment by blongho** [comment]
It works well for me. 
Do you have internet? 

Try to run this project [world-country-data-demo](https://github.com/blongho/world-country-data-demo) from your setup.  I followed the steps in the documentation and everything seem to work as expected. 

You can download the demo app from [World Country Data Demo app from Google Play Store](https://play.google.com/store/apps/details?id=com.blongho.countrydata )
